name: dm-tools # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Command-line tools for the lazy DM # 79 char long summary
description: |
  dm-tools is a role-playing combat encounter tracker and NPC generator for
  those who prefer a command line environment.

  Features auto-population of stats for SRD monsters, randomly-generated pocket
  items for NPCs, and several flavors of name generator algorithms.

  https://github.com/codyshepherd/dm-tools

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  dm-tools:
    python-version: python3
    source: .
    plugin: python
#  plebs:
#    python-version: python3
#    source: .
#    plugin: python
#  pockets:
#    python-version: python3
#    source: .
#    plugin: python
apps:
   live-game:
       command: bin/live-game
   plebs:
       command: bin/plebs
   pockets:
       command: bin/pockets
